// elencoV.js
const elencoV = [
  { nome: "Vespaziani Paola",       email: "paola.vespaziani@comune.frosinone.it",           telefono: "0775.265.6634", note: "UFFICIO COMMERCIO" },
  { nome: "Viscogliosi Giuseppe",   email: "giuseppe.viscogliosi@comune.frosinone.it",       telefono: "0775.265.6224", note: "" },
  { nome: "Vivenzio Vincenzo",      email: "vincenzo.vivenzio@comune.frosinone.it",          telefono: "0775.265.6574", note: "" }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoV;
