// elencoD.js
const elencoD = [
  { nome: "D'Agostini Angelo",        email: "angelo.dagostini@comune.frosinone.it",       telefono: "0775.265.6390", note: ""              },
  { nome: "D'Agostini Benedetta",     email: "benedetta.dagostini@comune.frosinone.it",    telefono: "0775.265.6637", note: ""              },
  { nome: "D'Arpino Sonia",           email: "sonia.darpino@comune.frosinone.it",          telefono: "0775.265.6695", note: ""              },
  { nome: "D'Emilia Maria",           email: "maria.demilia@comune.frosinone.it",          telefono: "0775.265.6519", note: "PENSIONE"       },
  { nome: "Damato Sandro",            email: "sandro.damato@comune.frosinone.it",          telefono: "0775.265.6644", note: ""              },
  { nome: "De Filippis Anna Maria",   email: "annamaria.defilippis@comune.frosinone.it",   telefono: "0775.265.6560", note: ""              },
  { nome: "De Luca Mario",            email: "mario.deluca@comune.frosinone.it",           telefono: "0775.265.6667", note: ""              },
  { nome: "De Podestà Emanuela",      email: "emanuela.depodesta@comune.frosinone.it",     telefono: "0775.265.6657", note: ""              },
  { nome: "De Simone Maria Teresa",   email: "mariateresa.desimone@comune.frosinone.it",   telefono: "0775.265.6457", note: "SERVIZI SOCIALI"},
  { nome: "Delfi Nicoletta",          email: "nicoletta.delfi@comune.frosinone.it",        telefono: "0775.265.6566", note: ""              },
  { nome: "Dell'Omo Gaspare",         email: "gaspare.dellomo@comune.frosinone.it",        telefono: "0775.265.6221", note: ""              },
  { nome: "Di Marco Daniela",         email: "daniela.dimarco@comune.frosinone.it",        telefono: "0775.265.6687", note: ""              },
  { nome: "Di Palma Salvatore",       email: "salvatore.dipalma@comune.frosinone.it",      telefono: "0775.265.6295", note: ""              },
  { nome: "Di Salvo Lucia",           email: "lucia.disalvo@comune.frosinone.it",          telefono: "0775.265.6386", note: ""              },
  { nome: "Di Virgilio Angela",       email: "angela.divirgilio@comune.frosinone.it",      telefono: "0775.265.6628", note: ""              }
];

// Esportazione per utilizzo esterno - blocato --> export default elencoD;
