// elencoT.js
const elencoT = [
  { nome: "Tagliaferri Gianni",      email: "gianni.tagliaferri@comune.frosinone.it",    telefono: "0775.265.6212", note: ""                     },
  { nome: "Tagliaferri Paolo",       email: "paolo.tagliaferri@comune.frosinone.it",     telefono: "0775.265.6533", note: ""                     },
  { nome: "Tagliaferri Valentina",   email: "valentina.tagliaferri@comune.frosinone.it", telefono: "0775.265.6565", note: "CED"                  },
  { nome: "Tata Pamela",             email: "pamela.tata@comune.frosinone.it",           telefono: "0775.265.6201", note: ""                     },
  { nome: "Tempesta Roberto",        email: "roberto.tempesta@comune.frosinone.it",      telefono: "0775.265.6235", note: ""                     },
  { nome: "Tesone Diana",            email: "diana.tesone@comune.frosinone.it",          telefono: "0775.265.6229", note: ""                     },
  { nome: "Tofani Giancarlo",        email: "giancarlo.tofani@comune.frosinone.it",      telefono: "0775.265.6345", note: ""                     },
  { nome: "Tosti Simona",            email: "simona.tosti@comune.frosinone.it",          telefono: "0775.265.6221", note: "TRASFERITA A CUNEO"   },
  { nome: "Tomaro Angelica",         email: "angelica.tomaro@comune.frosinone.it",       telefono: "0775.265.6636", note: ""                     },
  { nome: "Turriziani Cristiano",    email: "cristiano.turriziani@comune.frosinone.it",  telefono: "0775.265.6522", note: ""                     }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoT;
