// elencoS.js
const elencoS = [
  { nome: "Saiardi Valeria",           email: "valeria.saiardi@comune.frosinone.it",     telefono: "0775.265.6678", note: ""              },
  { nome: "Sannino Giovanni",          email: "giovanni.sannino@comune.frosinone.it",    telefono: "0775.265.6608", note: ""              },
  { nome: "Santoro Enrica",            email: "enrica.santoro@comune.frosinone.it",      telefono: "0775.265.6636", note: "PENSIONE"       },
  { nome: "Santoro Gian Marco",        email: "gianmarco.santoro@comune.frosinone.it",   telefono: "0775.265.6648", note: ""              },
  { nome: "Santucci Annarita",         email: "annarita.santucci@comune.frosinone.it",   telefono: "0775.265.6616", note: ""              },
  { nome: "Sarracino Giuseppe",        email: "giuseppe.sarracino@comune.frosinone.it",  telefono: "0775.265.6451", note: ""              },
  { nome: "Savoni Vanessa",            email: "vanessa.savoni@comune.frosinone.it",      telefono: "0775.265.6268", note: ""              },
  { nome: "Scaccia Simona",            email: "simona.scaccia@comune.frosinone.it",      telefono: "0775.265.6503", note: ""              },
  { nome: "Schiavi Eugenia",           email: "eugenia.schiavi@comune.frosinone.it",     telefono: "0775.265.6630", note: "PENSIONE"       },
  // Duplicato Schiavi Eugenia rimosso
  { nome: "Scirè Calabrisotto Andrea", email: "andrea.scire@comune.frosinone.it",       telefono: "0775.265.6349", note: ""              },
  { nome: "Sera Marisa",               email: "marisa.sera@comune.frosinone.it",         telefono: "0775.265.6575", note: ""              },
  { nome: "Sicilia Giulia",            email: "giulia.sicilia@comune.frosinone.it",      telefono: "0775.265.6632", note: ""              },
  { nome: "Silvestri Michela",         email: "michela.silvestri@comune.frosinone.it",   telefono: "0775.265.6229", note: "TRASFERITA A PISA" },
  { nome: "Simeoni Maria Grazia",      email: "mariagrazia.simeoni@comune.frosinone.it", telefono: "0775.265.6350", note: ""              },
  { nome: "Spaziani Alessandra",       email: "alessandra.spaziani@comune.frosinone.it", telefono: "0775.265.6602", note: "MANUTENZIONE"   },
  { nome: "Spaziani Antonella",        email: "antonella.spaziani@comune.frosinone.it",  telefono: "0775.265.6391", note: "ANAGRAFE"       },
  { nome: "Spaziani Andreina",         email: "andreina.spaziani@comune.frosinone.it",   telefono: "0775.265.63xx", note: "PENSIONE"       },
  { nome: "Spaziani Marco",            email: "marco.spaziani@comune.frosinone.it",      telefono: "0775.265.6227", note: "GEOLOGO AMBIENTE" },
  { nome: "Staff Sindaco",             email: "comunicazioni@comune.frosinone.it",       telefono: "0775.265.6503", note: ""              },
  { nome: "Strada Cristina",           email: "cristina.strada@comune.frosinone.it",     telefono: "0775.265.6660", note: ""              }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoS;
