// elencoQ.js
const elencoQ = [
  { nome: "Quadrozzi Assunta", email: "assunta.quadrozzi@comune.frosinone.it", telefono: "0775.265.6206", note: "PENSIONE" },
  { nome: "Quatrini Giuseppe", email: "giuseppe.quatrini@comune.frosinone.it", telefono: "0775.265.6668", note: ""          },
  { nome: "Quatrini Maurizio", email: "maurizio.quatrini@comune.frosinone.it", telefono: "0775.265.6469", note: ""          }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoQ;
