// elencoF.js
const elencoF = [
  { nome: "Falcone Luciano",     email: "luciano.falcone@comune.frosinone.it",     telefono: "0775.265.6387", note: "" },
  { nome: "Ferrante Giulio",     email: "giulio.ferrante@comune.frosinone.it",     telefono: "0775.265.6227", note: "" },
  { nome: "Ferrara Carmela",     email: "carmela.ferrara@comune.frosinone.it",     telefono: "0775.265.6517", note: "" },
  { nome: "Ferraro Alessandra",  email: "alessandra.ferraro@comune.frosinone.it",  telefono: "0775.265.6554", note: "" },
  { nome: "Ficco Sergio",        email: "sergio.ficco@comune.frosinone.it",        telefono: "0775.265.6452", note: "" },
  { nome: "Fioravanti Maurizio", email: "maurizio.fioravanti@comune.frosinone.it", telefono: "0775.265.6510", note: "" },
  { nome: "Fiorentini Emanuele", email: "emanuele.fiorentini@comune.frosinone.it", telefono: "0775.265.6511", note: "" },
  { nome: "Fornaro Salvatore",   email: "salvatore.fornaro@comune.frosinone.it",   telefono: "0775.265.6676", note: "" },
  { nome: "Fumagalli Silvia",    email: "silvia.fumagalli@comune.frosinone.it",    telefono: "0775.265.6678", note: "" }
];

// blocati ---> export default elencoF;
