// elencoN.js
const elencoN = [
  { nome: "Nichilò Valeria", email: "valeria.nichilo@comune.frosinone.it", telefono: "0775.265.6517", note: "TRASFERITA AD ALATRI" },
  { nome: "Noce Elio",       email: "elio.noce@comune.frosinone.it",        telefono: "0775.265.6219", note: "PENSIONE" },
  { nome: "Nobili Mario",    email: "",                                     telefono: "0775.265.62xx", note: "DECEDUTO" }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoN;
