// elencoR.js
const elencoR = [
  { nome: "Redolfi Roberto",    email: "roberto.redolfi@comune.frosinone.it",    telefono: "0775.265.6207", note: "" },
  { nome: "Ricci Sandro",       email: "sandro.ricci@comune.frosinone.it",       telefono: "0775.265.6567", note: "" },
  { nome: "Ritarossi Calberto", email: "calberto.ritarossi@comune.frosinone.it", telefono: "0775.265.6344", note: "" },
  { nome: "Rocca Lillo",        email: "lillo.rocca@comune.frosinone.it",        telefono: "0775.265.6231", note: "" },
  { nome: "Rosa Lucia",         email: "lucia.rosa@comune.frosinone.it",         telefono: "0775.265.6388", note: "" },
  { nome: "Rossi Walter",       email: "walter.rossi@comune.frosinone.it",       telefono: "0775.265.6444", note: "" },
  { nome: "Rossini Fabiola",    email: "fabiola.rossini@comune.frosinone.it",    telefono: "0775.265.6332", note: "" }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoR;
