// elencoP.js
const elencoP = [
  { nome: "Palmigiani Irene",  email: "irene.palmigiani@comune.frosinone.it",  telefono: "0775.265.6586", note: ""                },
  { nome: "Paniccia Rossana",  email: "rossana.paniccia@comune.frosinone.it",  telefono: "0775.265.6214", note: ""                },
  { nome: "Pantanella Sandra", email: "sandra.pantanella@comune.frosinone.it", telefono: "0775.265.6216", note: ""                },
  { nome: "Pascarella Sandra", email: "sandra.pascarella@comune.frosinone.it", telefono: "0775.265.6642", note: "POSTA E PROTOCOLLO" },
  { nome: "Pelagalli Italo",   email: "italo.pelagalli@comune.frosinone.it",   telefono: "0775.265.6226", note: "PENSIONE"           },
  { nome: "Piroli Gianluca",   email: "gianluca.piroli@comune.frosinone.it",   telefono: "0775.265.6649", note: ""                },
  { nome: "Porretta Pio",      email: "pio.porretta@comune.frosinone.it",      telefono: "0775.265.6211", note: ""                },
  { nome: "Potenti Annalisa",  email: "annalisa.potenti@comune.frosinone.it",  telefono: "0775.265.6333", note: ""                },
  { nome: "Pozzi Veronica",    email: "veronica.pozzi@comune.frosinone.it",    telefono: "0775.265.6459", note: ""                }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoP;
