// elencoD.js
const elencoE = [
  { nome: "Elicio Gianfranco",        email: "gianfranco.elicio@comune.frosinone.it",        telefono: "0775.265.6685", note: ""              },
  { nome: "Esposito Anna Maria",      email: "maria.esposito@comune.frosinone.it",          telefono: "0775.265.6686", note: ""              },
];

// Esportazione per utilizzo esterno - blocato --> export default elencoD;
