// elencoB.js
const elencoB = [
  { nome: "Baldassarre Luca",       email: "luca.baldassarre@comune.frosinone.it",       telefono: "0775.265.6665", note: "" },
  { nome: "Baldinelli Antonio",     email: "antonio.baldinelli@comune.frosinone.it",     telefono: "0775.265.6342", note: "" },
  { nome: "Bartolucci Barbara",     email: "barbara.bartolucci@comune.frosinone.it",     telefono: "0775.265.6455", note: "" },
  { nome: "Battiati Vincenza",      email: "vincenza.battiati@comune.frosinone.it",      telefono: "0775.265.6441", note: "" },
  { nome: "Bauco Damiano",          email: "damiano.bauco@comune.frosinone.it",          telefono: "0775.265.6242", note: "" },
  { nome: "Belli Ida",              email: "ida.belli@comune.frosinone.it",              telefono: "0775.265.6679", note: "" },
  { nome: "Bolella Romina",         email: "romina.bolella@comune.frosinone.it",         telefono: "0775.265.6271", note: "" },
  { nome: "Bonanno Cristina",       email: "cristina.bonanno@comune.frosinone.it",       telefono: "0775.265.6339", note: "" },
  { nome: "Bove Marilena",          email: "mariolena.bove@comune.frosinone.it",         telefono: "0775.265.6680", note: "" },
  { nome: "Bracaglia Cesare",       email: "cesare.bracaglia@comune.frosinone.it",       telefono: "0775.265.6203", note: "CASE POPOLARI" },
  { nome: "Bracaglia Sisto",        email: "sisto.bracaglia@comune.frosinone.it",        telefono: "0775.265.6502", note: "" },
  { nome: "Brugnoli Paola",         email: "paola.brugnoli@comune.frosinone.it",         telefono: "0775.265.6661", note: "" }
];

// blocati export default elencoB;
