// elencoM.js
const elencoM = [
  { nome: "Magliocchetti Anna",  email: "anna.magliocchetti@comune.frosinone.it",  telefono: "0775.265.6280", note: "" },
  { nome: "Manchi Andrea",       email: "andrea.manchi@comune.frosinone.it",       telefono: "0775.265.6603", note: "" },
  { nome: "Marini Guglielmo",    email: "guglielmo.marini@comune.frosinone.it",    telefono: "0775.265.6259", note: "" },
  { nome: "Marrocco Armando",    email: "armando.marrocco@comune.frosinone.it",    telefono: "0775.265.6443", note: "" },
  { nome: "Martino Francesca",   email: "francesca.martino@comune.frosinone.it",   telefono: "0775.265.6546", note: "" },
  { nome: "Marucci Emanuela",    email: "emanuela.marucci@comune.frosinone.it",    telefono: "0775.265.6610", note: "" },
  { nome: "Masi Alessia",        email: "alessia.masi@comune.frosinone.it",        telefono: "0775.265.6500", note: "" },
  { nome: "Mattone Rosalia",     email: "rosalia.mattone@comune.frosinone.it",     telefono: "0775.265.6542", note: "" },
  { nome: "Mauro Donato",        email: "donato.mauro@comune.frosinone.it",        telefono: "0775.265.6340", note: "" },
  { nome: "Mazzeo Anna",         email: "anna.mazzeo@comune.frosinone.it",         telefono: "0775.265.6464", note: "" },
  { nome: "Mercado Veronica",    email: "veronica.mercado@comune.frosinone.it",    telefono: "0775.265.6640", note: "" },
  { nome: "Messia Alfredo",      email: "alfredo.messia@comune.frosinone.it",      telefono: "0775.265.6693", note: "" },
  { nome: "Montuori Patrizia",   email: "patrizia.montuori@comune.frosinone.it",   telefono: "0775.265.6620", note: "" },
  { nome: "Morini Monia",        email: "monia.morini@comune.frosinone.it",        telefono: "0775.265.6684", note: "" },
  { nome: "Muccillo Giulia",     email: "giulia.muccillo@comune.frosinone.it",     telefono: "0775.265.6514", note: "" }
];

// Esportazione per utilizzo esterno - bloccato --> export default elencoM;
