@REM  cd.. devi posizionarti su git_desktop
@REM  EMAIL		: icivix@libero.it
@REM  PASSWORD	: :yRch3VbGhX6iLr

CD c:\GESTIONI\GESTIONE_LLPP\25_GESTIONE_LLPP\PRES3000_GESTIONE\ARCHIVI_PRES3000\PRES3000_NUMERI_TELEFONICI_DIPENDENTI\

dir 

@ECHO  APRO OVERLEAF MENU
@ECHO  .......................................................
@ECHO  .
@ECHO  .
@ECHO  .
start msedge --profile-directory="Personale" https://www.overleaf.com/project/673f14af2c91e5134eb44afa	
@ECHO  .
@ECHO  .
@ECHO  .......................................................


@rem pausa di 2 secondi per consentire il commit

@REM 01)
@REM sospensione per 1 secondo con crononometro 
@REM ---->	timeout /t 2 /nobreak > NUL
@REM ---->
ECHO
ECHO
ECHO  pausa di 2 secondi per consentire il commit
ECHO
@TIMEOUT /T 2 /NOBREAK

